name: Publish
on:
  push:
    branches:
     - main
  workflow_dispatch:
  schedule:
   - cron: '*/5 * * * *'
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: zulip/zulip-archive@master
      with:
        zuliprc: ${{ secrets.ZULIPRC }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        delete_history: false
        archive_branch: main
