name: Publish
on:
  workflow_dispatch:
  schedule:
   - cron: '*/5 * * * *'
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: zulip/zulip-archive@master
      with:
        zuliprc: ${{ secrets.ZULIPRC }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # delete_history: true # may eventually need to enable this to save space
        archive_branch: main
